// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nact from "../lib/nact/Nact.res.mjs";

var system = Nact.start(undefined, undefined, undefined);

function wait(timeout) {
  return new Promise((function (resolve, param) {
                setTimeout(resolve, timeout);
              }));
}

var ping = Nact.spawnStateless("ping", undefined, system, (async function (param, ctx) {
        console.log(param._1);
        await wait(100);
        return Nact.dispatch(param._0, {
                    TAG: "Msg",
                    _0: ctx.self,
                    _1: ctx.name
                  });
      }));

var pong = Nact.spawnStateless("pong", undefined, system, (async function (param, ctx) {
        console.log(param._1);
        await wait(100);
        return Nact.dispatch(param._0, {
                    TAG: "Msg",
                    _0: ctx.self,
                    _1: ctx.name
                  });
      }));

Nact.dispatch(ping, {
      TAG: "Msg",
      _0: pong,
      _1: "hello"
    });

setTimeout((function () {
        console.log("STOP");
        Nact.stop(system);
      }), 1000);

export {
  system ,
  wait ,
  ping ,
  pong ,
}
/* system Not a pure module */
