// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nact = require("../lib/nact/Nact.res.js");

var system = Nact.start(undefined, undefined, undefined);

var ping = Nact.spawnStateless("ping", undefined, system, (async function (param, ctx) {
        console.log(param._1);
        return Nact.dispatch(param._0, {
                    TAG: "Msg",
                    _0: ctx.self,
                    _1: ctx.name
                  });
      }));

var pong = Nact.spawnStateless("pong", undefined, system, (async function (param, ctx) {
        console.log(param._1);
        return Nact.dispatch(param._0, {
                    TAG: "Msg",
                    _0: ctx.self,
                    _1: ctx.name
                  });
      }));

Nact.dispatch(ping, {
      TAG: "Msg",
      _0: pong,
      _1: "hello"
    });

setTimeout((function () {
        Nact.stop(system);
      }), 100);

exports.system = system;
exports.ping = ping;
exports.pong = pong;
/* system Not a pure module */
