// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nact = require("../lib/nact/Nact.res.js");

var system = Nact.start(undefined, undefined, undefined);

exports.system = system;
/* system Not a pure module */
