// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nact from "../lib/nact/Nact.res.mjs";

function validateLumerosUpd(param, x) {
  var cur = param.resources.lumeros;
  return (cur._0 + x._0 | 0) >= 0;
}

function validateMoxalinUpd(param, x) {
  var cur = param.resources.moxalin;
  return (cur._0 + x._0 | 0) >= 0;
}

function validateEvedamiaUpd(param, x) {
  var cur = param.resources.evedamia;
  return (cur._0 + x._0 | 0) >= 0;
}

function addLumeros(param, x) {
  var resources = param.resources;
  var curCount = resources.lumeros;
  return {
          resources: {
            evedamia: resources.evedamia,
            moxalin: resources.moxalin,
            lumeros: {
              TAG: "Lumeros",
              _0: curCount._0 + x._0 | 0
            }
          }
        };
}

function addEvedamia(param, x) {
  var resources = param.resources;
  var curCount = resources.evedamia;
  return {
          resources: {
            evedamia: {
              TAG: "Evedamia",
              _0: curCount._0 + x._0 | 0
            },
            moxalin: resources.moxalin,
            lumeros: resources.lumeros
          }
        };
}

function addMoxalin(param, x) {
  var resources = param.resources;
  var curCount = resources.moxalin;
  return {
          resources: {
            evedamia: resources.evedamia,
            moxalin: {
              TAG: "Moxalin",
              _0: curCount._0 + x._0 | 0
            },
            lumeros: resources.lumeros
          }
        };
}

function make(game, playerId) {
  return Nact.spawn(playerId, undefined, undefined, game, (async function (state, param, param$1) {
                var msg = param[1];
                var sender = param[0];
                switch (msg.TAG) {
                  case "AddLumeros" :
                      var l = msg._0;
                      if (validateLumerosUpd(state, l)) {
                        Nact.dispatch(sender, {
                              TAG: "Ok",
                              _0: undefined
                            });
                        return addLumeros(state, l);
                      } else {
                        Nact.dispatch(sender, {
                              TAG: "Error",
                              _0: "InsufficientError"
                            });
                        return state;
                      }
                  case "AddEvedamia" :
                      var e = msg._0;
                      if (validateEvedamiaUpd(state, e)) {
                        Nact.dispatch(sender, {
                              TAG: "Ok",
                              _0: undefined
                            });
                        return addEvedamia(state, e);
                      } else {
                        Nact.dispatch(sender, {
                              TAG: "Error",
                              _0: "InsufficientError"
                            });
                        return state;
                      }
                  case "AddMoxalin" :
                      var m = msg._0;
                      if (validateMoxalinUpd(state, m)) {
                        Nact.dispatch(sender, {
                              TAG: "Ok",
                              _0: undefined
                            });
                        return addMoxalin(state, m);
                      } else {
                        Nact.dispatch(sender, {
                              TAG: "Error",
                              _0: "InsufficientError"
                            });
                        return state;
                      }
                  
                }
              }), (function (param) {
                return {
                        resources: {
                          evedamia: {
                            TAG: "Evedamia",
                            _0: 0
                          },
                          moxalin: {
                            TAG: "Moxalin",
                            _0: 0
                          },
                          lumeros: {
                            TAG: "Lumeros",
                            _0: 1000
                          }
                        }
                      };
              }));
}

export {
  validateLumerosUpd ,
  validateMoxalinUpd ,
  validateEvedamiaUpd ,
  addLumeros ,
  addEvedamia ,
  addMoxalin ,
  make ,
}
/* Nact Not a pure module */
